const DIVIDER = '━━━━━━━━━━━━━━━━━━';
const THIN_DIVIDER = '────────────────────';

/**
 * Escape text before placing it inside Telegram HTML.
 *
 * This prevents product names, customer names or other
 * dynamic content from accidentally breaking HTML formatting.
 */
function escapeHtml(str = '') {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Convert a value into a safe Telegram HTML text.
 */
function safeText(value = '') {
  return escapeHtml(value);
}

/**
 * Format price consistently.
 *
 * Example:
 * 199 -> ১৯৯৳
 */
function formatPrice(price) {
  const amount = Number(price);

  if (!Number.isFinite(amount)) {
    return '৳0';
  }

  return `৳${amount}`;
}

/**
 * Bangladesh date/time.
 */
function nowBD() {
  return new Date().toLocaleString('en-BD', {
    timeZone: 'Asia/Dhaka',
    dateStyle: 'medium',
    timeStyle: 'short'
  });
}

/**
 * Generate a unique-looking order ID.
 *
 * Order IDs are generated by the application only.
 * AI must never generate or invent order IDs.
 */
function generateOrderId() {
  const timestamp = Date.now().toString().slice(-8);
  const random = Math.floor(10 + Math.random() * 90);

  return `ORD-${timestamp}${random}`;
}

/**
 * Create a professional section heading.
 */
function sectionTitle(icon, title) {
  return `${icon} <b>${escapeHtml(title)}</b>`;
}

/**
 * Create a clean product title.
 */
function productTitle(product, number = null) {
  const prefix = number !== null ? `${number}. ` : '';

  return `${prefix}<b>${escapeHtml(
    product?.shortTitle || product?.title || 'Product'
  )}</b>`;
}

/**
 * Create a compact price line.
 */
function priceLine(price) {
  return `💰 <b>মূল্য:</b> ${formatPrice(price)}`;
}

/**
 * Create a professional product card body.
 *
 * Payment/contact numbers are intentionally NOT included here.
 * They should only be displayed when the customer explicitly
 * asks for the relevant payment/contact number.
 */
function productCardText(product, orderId = '') {
  const title = product?.shortTitle || product?.title || 'Product';
  const price = formatPrice(product?.price);

  const lines = [
    '📦 <b>Course / Product Details</b>',
    DIVIDER,
    `📚 <b>${escapeHtml(title)}</b>`,
    `💰 <b>মূল্য:</b> ${price}`
  ];

  if (orderId) {
    lines.push(`🆔 <b>Order ID:</b> <code>${escapeHtml(orderId)}</code>`);
  }

  lines.push(
    THIN_DIVIDER,
    '💳 <b>Payment:</b> পেমেন্ট করার আগে নিচের নির্দেশনা অনুসরণ করুন।',
    '📸 পেমেন্টের পর <b>Transaction ID</b> এবং <b>Payment Screenshot</b> পাঠান।',
    '⚡ Verification সম্পন্ন হলে অর্ডার প্রসেস করা হবে।'
  );

  return lines.join('\n');
}

/**
 * Clean Telegram HTML wrapper.
 */
function htmlMessage(title, body, icon = '📌') {
  return [
    `${icon} <b>${escapeHtml(title)}</b>`,
    DIVIDER,
    body
  ].join('\n');
}

module.exports = {
  DIVIDER,
  THIN_DIVIDER,
  escapeHtml,
  safeText,
  formatPrice,
  nowBD,
  generateOrderId,
  sectionTitle,
  productTitle,
  priceLine,
  productCardText,
  htmlMessage
};
